#define _POSIX_C_SOURCE 200809L
#undef UNICODE
#undef _UNICODE
#include <windows.h>
#include <commctrl.h>
#include <commdlg.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "../win32/gucedit.h"
#include "c_lex.h"
#include "document.h"
#include "styles.h"

#define WM_RESTYLE (WM_APP + 0x18)
enum { ID_EDIT=100,ID_STATUS,ID_NEW=200,ID_OPEN,ID_SAVE,ID_SAVEAS,ID_EXIT,
 ID_UNDO,ID_CUT,ID_COPY,ID_PASTE,ID_SELECTALL,ID_FIND,ID_GOTO,ID_REFRESH,ID_ABOUT };
static HWND win,edit,status; static SeditDocument doc; static SeditLexer lex;
static char *scan_text; static size_t scan_len,scan_off; static UINT scan_gen,wanted_gen;
static int scan_active,restyle_posted,destroying; static uint32_t goto_line=1;
static HWND goto_dlg; static int goto_done,goto_ok; static char goto_input[1200];
static HWND find_dlg; static int find_done,find_ok; static char find_input[512];

static void status_text(const char*s){SendMessage(status,SB_SETTEXTA,0,(LPARAM)s);}
static const char*eol_name(void){return doc.eol==SEDIT_EOL_CRLF?"CRLF":doc.eol==SEDIT_EOL_CR?"CR":"LF";}
static void title(void){char b[1200];const char*p=doc.user_path[0]?doc.user_path:"Untitled";snprintf(b,sizeof b,"%s%s - Source Editor",doc.dirty?"*":"",p);SetWindowText(win,b);char q[1200];snprintf(q,sizeof q,"Line %u | %s | UTF-8%s | %s",goto_line,eol_name(),doc.bom?" BOM":"",doc.target_path[0]?doc.target_path:"new file");status_text(q);}
static void get_text(char**p,size_t*n){int z=GetWindowTextLength(edit);char*b=malloc((size_t)z+1);if(!b){*p=NULL;*n=0;return;}GetWindowText(edit,b,z+1);*p=b;*n=(size_t)z;}
static void cancel_scan(void){free(scan_text);scan_text=NULL;scan_len=scan_off=0;sedit_lex_free(&lex);scan_active=0;}
static void post_restyle(void){if(!restyle_posted&&!destroying){restyle_posted=1;PostMessage(win,WM_RESTYLE,0,0);}}
static void publish_styles(void){
 DWORD a=0,z=0;SendMessage(edit,EM_GETSEL,(WPARAM)&a,(LPARAM)&z);int truncated=0;
 GUCEDIT_BATCH_V1*b=sedit_styles_build(&lex,scan_text,scan_len,(uint32_t)z,scan_gen,&truncated);
 if(!b){status_text("Highlighting unavailable: out of memory");return;}
 if(!SendMessage(edit,GEM_SETSTYLES,0,(LPARAM)b))status_text(GetLastError()==GUCEDIT_ERROR_STALE_GENERATION?"Highlighting restarted after edit":"Highlighting unavailable");
 else if(truncated)status_text("Highlighting truncated: style limit reached");
 free(b);
}
static void restyle_step(void){
 restyle_posted=0;UINT g=(UINT)SendMessage(edit,GEM_GETTEXTGEN,0,0);if(scan_active&&g!=scan_gen)cancel_scan();
 if(!scan_active){UINT g1=g;get_text(&scan_text,&scan_len);UINT g2=(UINT)SendMessage(edit,GEM_GETTEXTGEN,0,0);if(!scan_text)return;if(g1!=g2||g2!=wanted_gen){free(scan_text);scan_text=NULL;post_restyle();return;}scan_gen=g2;scan_off=0;sedit_lex_init(&lex);scan_active=1;}
 struct timespec begun,now;clock_gettime(CLOCK_MONOTONIC,&begun);size_t turn_start=scan_off;
 do{size_t end=scan_off+32768;if(end>scan_len)end=scan_len;
 if(!sedit_lex_feed(&lex,scan_text+scan_off,end-scan_off)){status_text("Highlighting unavailable: out of memory");cancel_scan();return;}scan_off=end;
 clock_gettime(CLOCK_MONOTONIC,&now);
 }while(scan_off<scan_len&&scan_off-turn_start<262144&&
        (now.tv_sec-begun.tv_sec)*1000000000LL+now.tv_nsec-begun.tv_nsec<8000000LL);
 if(scan_off<scan_len){post_restyle();return;}if(!sedit_lex_finish(&lex)){cancel_scan();return;}if((UINT)SendMessage(edit,GEM_GETTEXTGEN,0,0)==scan_gen)publish_styles();scan_active=0; /* keep lexer/pairs + snapshot for Ctrl+] */
}
static int choose_eol(enum SeditEol*out){int r=MessageBox(win,"Mixed line endings. Yes: Edit and save as LF\nNo: choose CRLF or CR\nCancel: leave untouched","Mixed EOL",MB_YESNOCANCEL);if(r==IDCANCEL)return 0;if(r==IDYES){*out=SEDIT_EOL_LF;return 1;}r=MessageBox(win,"Yes: Edit and save as CRLF\nNo: Edit and save as CR","Mixed EOL",MB_YESNO);*out=r==IDYES?SEDIT_EOL_CRLF:SEDIT_EOL_CR;return 1;}
static int open_path(const char*p,uint32_t line){SeditDocument nd;sedit_document_init(&nd);if(sedit_document_load(&nd,p)){MessageBox(win,nd.error,"Source Editor - Open",MB_OK);sedit_document_free(&nd);return 0;}uint32_t off,lines;if(sedit_document_line_offset(nd.text,nd.len,line,&off,&lines)){char b[128];snprintf(b,sizeof b,"location line %u exceeds %u",line,lines);MessageBox(win,b,"Source Editor",MB_OK);sedit_document_free(&nd);return 0;}if(nd.eol==SEDIT_EOL_MIXED&&!choose_eol(&nd.eol)){sedit_document_free(&nd);return 0;}sedit_document_free(&doc);doc=nd;SetWindowText(edit,doc.text);SendMessage(edit,EM_SETMODIFY,FALSE,0);SendMessage(edit,EM_SETSEL,off,off);goto_line=line;wanted_gen=(UINT)SendMessage(edit,GEM_GETTEXTGEN,0,0);post_restyle();title();return 1;}
static int choose_file(int save,char*out,size_t cap){WCHAR w[1024]={0};OPENFILENAMEW o;memset(&o,0,sizeof o);o.lStructSize=sizeof o;o.hwndOwner=win;o.lpstrFile=w;o.nMaxFile=1024;o.lpstrDefExt=u"c";o.lpstrTitle=save?u"Save Source As":u"Open Source";o.Flags=save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST;BOOL ok=save?GetSaveFileNameW(&o):GetOpenFileNameW(&o);if(!ok)return 0;WideCharToMultiByte(CP_UTF8,0,w,-1,out,(int)cap,NULL,NULL);out[cap-1]=0;return 1;}
static int save_doc(int as){char path[1024];const char*p=NULL;if(as||!doc.target_path[0]){if(!choose_file(1,path,sizeof path))return 0;p=path;}char*t;size_t n;get_text(&t,&n);if(!t)return 0;enum SeditSaveResult r=sedit_document_save(&doc,p,t,n,0,0);if(r==SEDIT_SAVE_CONFLICT){char m[1400];snprintf(m,sizeof m,"The physical target changed:\n%s\n\nYes: Overwrite\nNo: Save As\nCancel: keep editing",doc.target_path);int q=MessageBox(win,m,"External conflict",MB_YESNOCANCEL);if(q==IDYES)r=sedit_document_save(&doc,NULL,t,n,1,0);else if(q==IDNO){free(t);return save_doc(1);}else{free(t);return 0;}}if(r==SEDIT_SAVE_HARDLINK){char m[256];snprintf(m,sizeof m,"Atomic save would break %lu hard links.\nBreak Links and Save?",(unsigned long)doc.opened_stat.st_nlink);if(MessageBox(win,m,"Hard links",MB_YESNO)==IDYES)r=sedit_document_save(&doc,p,t,n,0,1);}free(t);if(r!=SEDIT_SAVE_OK){if(r==SEDIT_SAVE_ERROR)MessageBox(win,doc.error,"Save failed",MB_OK);else if(r==SEDIT_SAVE_PUBLISHED_REFRESH_FAILED)MessageBox(win,doc.error,"Saved, but identity refresh failed",MB_OK);return 0;}SendMessage(edit,EM_SETMODIFY,FALSE,0);doc.dirty=0;title();return 1;}
static int may_close(void){if(!doc.dirty)return 1;int r=MessageBox(win,"Save changes?","Source Editor",MB_YESNOCANCEL);return r==IDNO||(r==IDYES&&save_doc(0));}
/* Both dialog procs act on BN_CLICKED only: the input EDIT is control id 2
 * == IDCANCEL, so its EN_CHANGE notifications (HIWORD != BN_CLICKED) would
 * otherwise read as Cancel and close the dialog on the first keystroke. */
static LRESULT GotoProc(HWND h,UINT m,WPARAM w,LPARAM l){(void)l;switch(m){case WM_CREATE:CreateWindowEx(0,"STATIC","Line, FILE:LINE, or one cc diagnostic:",WS_CHILD|WS_VISIBLE,12,10,430,20,h,(HMENU)1,NULL,NULL);goto_dlg=CreateWindowEx(0,"EDIT","",WS_CHILD|WS_VISIBLE|WS_TABSTOP|WS_BORDER,12,34,430,26,h,(HMENU)2,NULL,NULL);CreateWindowEx(0,"BUTTON","Go",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,270,70,80,28,h,(HMENU)IDOK,NULL,NULL);CreateWindowEx(0,"BUTTON","Cancel",WS_CHILD|WS_VISIBLE|WS_TABSTOP,360,70,80,28,h,(HMENU)IDCANCEL,NULL,NULL);SetFocus(goto_dlg);return 0;case WM_COMMAND:if(HIWORD(w)==BN_CLICKED&&(LOWORD(w)==IDOK||LOWORD(w)==IDCANCEL)){goto_ok=LOWORD(w)==IDOK;if(goto_ok)GetWindowTextA(goto_dlg,goto_input,sizeof goto_input);goto_done=1;DestroyWindow(h);}return 0;case WM_CLOSE:goto_ok=0;goto_done=1;DestroyWindow(h);return 0;}return DefWindowProc(h,m,w,l);}
static LRESULT FindProc(HWND h,UINT m,WPARAM w,LPARAM l){(void)l;switch(m){case WM_CREATE:CreateWindowEx(0,"STATIC","Find text:",WS_CHILD|WS_VISIBLE,12,10,430,20,h,(HMENU)1,NULL,NULL);find_dlg=CreateWindowEx(0,"EDIT",find_input,WS_CHILD|WS_VISIBLE|WS_TABSTOP|WS_BORDER,12,34,430,26,h,(HMENU)2,NULL,NULL);CreateWindowEx(0,"BUTTON","Find Next",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,270,70,80,28,h,(HMENU)IDOK,NULL,NULL);CreateWindowEx(0,"BUTTON","Cancel",WS_CHILD|WS_VISIBLE|WS_TABSTOP,360,70,80,28,h,(HMENU)IDCANCEL,NULL,NULL);SendMessage(find_dlg,EM_SETSEL,0,-1);SetFocus(find_dlg);return 0;case WM_COMMAND:if(HIWORD(w)==BN_CLICKED&&(LOWORD(w)==IDOK||LOWORD(w)==IDCANCEL)){find_ok=LOWORD(w)==IDOK;if(find_ok)GetWindowTextA(find_dlg,find_input,sizeof find_input);find_done=1;DestroyWindow(h);}return 0;case WM_CLOSE:find_ok=0;find_done=1;DestroyWindow(h);return 0;}return DefWindowProc(h,m,w,l);}
static int prompt_find(void){find_done=find_ok=0;HWND d=CreateWindowEx(0,"SeditFind","Find",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_VISIBLE,130,120,470,135,win,NULL,NULL,NULL);if(!d)return 0;EnableWindow(win,FALSE);MSG m;while(!find_done&&GetMessage(&m,NULL,0,0)){if(m.message==WM_KEYDOWN&&(m.wParam==VK_RETURN||m.wParam==VK_ESCAPE)){SendMessage(d,WM_COMMAND,m.wParam==VK_RETURN?IDOK:IDCANCEL,0);continue;}TranslateMessage(&m);DispatchMessage(&m);}EnableWindow(win,TRUE);SetFocus(edit);if(!find_ok||!find_input[0])return 0;char*t;size_t n;get_text(&t,&n);if(!t)return 0;DWORD a,z;SendMessage(edit,EM_GETSEL,(WPARAM)&a,(LPARAM)&z);char*p=strstr(t+(z<=n?z:0),find_input);if(!p)p=strstr(t,find_input);if(!p){MessageBeep(MB_OK);free(t);return 0;}DWORD at=(DWORD)(p-t),end=at+(DWORD)strlen(find_input);SendMessage(edit,EM_SETSEL,at,end);free(t);publish_styles();return 1;}
static int prompt_line(void){char path[1024];uint32_t line=0;goto_done=goto_ok=0;goto_input[0]=0;HWND d=CreateWindowEx(0,"SeditGoto","Go to line",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_VISIBLE,130,120,470,135,win,NULL,NULL,NULL);if(!d)return 0;EnableWindow(win,FALSE);MSG m;while(!goto_done&&GetMessage(&m,NULL,0,0)){TranslateMessage(&m);DispatchMessage(&m);}EnableWindow(win,TRUE);SetFocus(edit);if(!goto_ok)return 0;
 int digits=goto_input[0]!=0;uint64_t v=0;for(char*q=goto_input;*q;q++){if(*q<'0'||*q>'9'){digits=0;break;}v=v*10+(unsigned)(*q-'0');if(v>UINT32_MAX){digits=0;break;}}if(digits&&v){line=(uint32_t)v;snprintf(path,sizeof path,"%s",doc.user_path);}else if(sedit_document_diagnostic(goto_input,path,sizeof path,&line)&&sedit_document_location(goto_input,path,sizeof path,&line)){MessageBox(win,"Expected a positive line, FILE:LINE, or one complete cc diagnostic.","Go to line",MB_OK);return 0;}
 char real[1024];if(!digits){if(!realpath(path,real)){char b[1400];snprintf(b,sizeof b,"Cannot open location '%s': %s",path,strerror(errno));MessageBox(win,b,"Go to line",MB_OK);return 0;}if(strcmp(real,doc.target_path)){if(!may_close())return 0;return open_path(path,line);}}char*current;size_t current_n;get_text(&current,&current_n);if(!current)return 0;DWORD a,z;SendMessage(edit,EM_GETSEL,(WPARAM)&a,(LPARAM)&z);uint32_t off=(uint32_t)z,nav=goto_line,lines=0;if(sedit_navigation_apply(current,current_n,line,&off,&nav,&lines)){char b[128];snprintf(b,sizeof b,"location line %u exceeds %u",line,lines);free(current);MessageBox(win,b,"Go to line",MB_OK);return 0;}free(current);SendMessage(edit,EM_SETSEL,off,off);goto_line=nav;title();publish_styles();return 1;}
static void jump_match(int extend){DWORD a,z;SendMessage(edit,EM_GETSEL,(WPARAM)&a,(LPARAM)&z);uint32_t p=z,at=UINT32_MAX,m;int u;if(scan_text&&p<scan_len&&strchr("()[]{}",scan_text[p]))at=p;else if(scan_text&&p&&strchr("()[]{}",scan_text[p-1]))at=p-1;if(at!=UINT32_MAX&&sedit_pair_mate(&lex,at,&m,&u)&&!u)SendMessage(edit,EM_SETSEL,extend?a:m, m);else MessageBeep(MB_OK);publish_styles();}
static HMENU menu_build(void){HMENU bar=CreateMenu(),f=CreatePopupMenu(),e=CreatePopupMenu(),s=CreatePopupMenu(),h=CreatePopupMenu();AppendMenuA(f,MF_STRING,ID_NEW,"&New\tCtrl+N");AppendMenuA(f,MF_STRING,ID_OPEN,"&Open...\tCtrl+O");AppendMenuA(f,MF_STRING,ID_SAVE,"&Save\tCtrl+S");AppendMenuA(f,MF_STRING,ID_SAVEAS,"Save &As...\tCtrl+Shift+S");AppendMenuA(f,MF_SEPARATOR,0,NULL);AppendMenuA(f,MF_STRING,ID_EXIT,"E&xit");AppendMenuA(e,MF_STRING,ID_UNDO,"&Undo\tCtrl+Z");AppendMenuA(e,MF_STRING,ID_CUT,"Cu&t\tCtrl+X");AppendMenuA(e,MF_STRING,ID_COPY,"&Copy\tCtrl+C");AppendMenuA(e,MF_STRING,ID_PASTE,"&Paste\tCtrl+V");AppendMenuA(e,MF_STRING,ID_SELECTALL,"Select &All\tCtrl+A");AppendMenuA(s,MF_STRING,ID_FIND,"&Find...\tCtrl+F");AppendMenuA(s,MF_STRING,ID_GOTO,"&Go to line...\tCtrl+G");AppendMenuA(s,MF_STRING,ID_REFRESH,"&Refresh Highlighting");AppendMenuA(h,MF_STRING,ID_ABOUT,"&About");AppendMenuA(bar,MF_POPUP,(UINT_PTR)f,"&File");AppendMenuA(bar,MF_POPUP,(UINT_PTR)e,"&Edit");AppendMenuA(bar,MF_POPUP,(UINT_PTR)s,"&Search");AppendMenuA(bar,MF_POPUP,(UINT_PTR)h,"&Help");return bar;}
static LRESULT WndProc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:edit=CreateWindowEx(0,"EDIT","",WS_CHILD|WS_VISIBLE|WS_TABSTOP|WS_VSCROLL|WS_HSCROLL|ES_MULTILINE|ES_AUTOHSCROLL,0,0,100,100,h,(HMENU)ID_EDIT,NULL,NULL);status=CreateStatusWindowA(WS_CHILD|WS_VISIBLE|CCS_BOTTOM,"",h,ID_STATUS);SetFocus(edit);return 0;case WM_SIZE:{RECT r;GetClientRect(h,&r);MoveWindow(status,0,r.bottom-24,r.right,24,TRUE);MoveWindow(edit,0,0,r.right,r.bottom-24,TRUE);return 0;}case WM_COMMAND:if((HWND)l==edit&&HIWORD(w)==EN_CHANGE){doc.dirty=SendMessage(edit,EM_GETMODIFY,0,0)!=0;wanted_gen=(UINT)SendMessage(edit,GEM_GETTEXTGEN,0,0);cancel_scan();post_restyle();title();return 0;}switch(LOWORD(w)){case ID_NEW:if(may_close()){sedit_document_new(&doc);SetWindowText(edit,"");SendMessage(edit,EM_SETMODIFY,FALSE,0);doc.dirty=0;title();}break;case ID_OPEN:{if(!may_close())break;char p[1024];if(choose_file(0,p,sizeof p))open_path(p,1);break;}case ID_SAVE:save_doc(0);break;case ID_SAVEAS:save_doc(1);break;case ID_EXIT:if(may_close())DestroyWindow(h);break;case ID_UNDO:SendMessage(edit,EM_UNDO,0,0);break;case ID_CUT:SendMessage(edit,WM_CUT,0,0);break;case ID_COPY:SendMessage(edit,WM_COPY,0,0);break;case ID_PASTE:SendMessage(edit,WM_PASTE,0,0);break;case ID_SELECTALL:SendMessage(edit,EM_SETSEL,0,-1);break;case ID_FIND:prompt_find();break;case ID_GOTO:prompt_line();break;case ID_REFRESH:wanted_gen=(UINT)SendMessage(edit,GEM_GETTEXTGEN,0,0);cancel_scan();post_restyle();break;case ID_ABOUT:MessageBox(h,"Source Editor — C-aware editor for gucOS.","About",MB_OK);break;}return 0;case WM_RESTYLE:restyle_step();return 0;case WM_CLOSE:if(may_close())DestroyWindow(h);return 0;case WM_DESTROY:destroying=1;cancel_scan();PostQuitMessage(0);return 0;}return DefWindowProc(h,m,w,l);}
int main(int argc,char**argv){sedit_document_init(&doc);sedit_document_new(&doc);WNDCLASS c;memset(&c,0,sizeof c);c.lpfnWndProc=WndProc;c.lpszClassName="Sedit";c.hbrBackground=(HBRUSH)(COLOR_BTNFACE+1);if(!RegisterClass(&c))return 3;WNDCLASS g;memset(&g,0,sizeof g);g.lpfnWndProc=GotoProc;g.lpszClassName="SeditGoto";g.hbrBackground=(HBRUSH)(COLOR_BTNFACE+1);if(!RegisterClass(&g))return 3;g.lpfnWndProc=FindProc;g.lpszClassName="SeditFind";if(!RegisterClass(&g))return 3;win=CreateWindowEx(0,"Sedit","Untitled - Source Editor",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_VISIBLE,80,60,760,560,NULL,menu_build(),NULL,NULL);if(!win)return 3;ACCEL aa[]={{FVIRTKEY|FCONTROL,'N',ID_NEW},{FVIRTKEY|FCONTROL,'O',ID_OPEN},{FVIRTKEY|FCONTROL,'S',ID_SAVE},{FVIRTKEY|FCONTROL|FSHIFT,'S',ID_SAVEAS},{FVIRTKEY|FCONTROL,'F',ID_FIND},{FVIRTKEY|FCONTROL,'G',ID_GOTO},{FVIRTKEY|FCONTROL,'Z',ID_UNDO},{FVIRTKEY|FCONTROL,'X',ID_CUT},{FVIRTKEY|FCONTROL,'C',ID_COPY},{FVIRTKEY|FCONTROL,'V',ID_PASTE},{FVIRTKEY|FCONTROL,'A',ID_SELECTALL}};HACCEL ha=CreateAcceleratorTableA(aa,sizeof aa/sizeof aa[0]);if(argc>1){char p[1024];uint32_t line;if(sedit_document_location(argv[1],p,sizeof p,&line)||!open_path(p,line)){DestroyWindow(win);return 2;}}else{wanted_gen=(UINT)SendMessage(edit,GEM_GETTEXTGEN,0,0);post_restyle();title();}MSG m;while(GetMessage(&m,NULL,0,0)){UINT dispatched=m.message;HWND target=m.hwnd;if((GetKeyState(VK_CONTROL)&0x8000)&&m.message==WM_KEYDOWN&&m.wParam==VK_OEM_6){jump_match((GetKeyState(VK_SHIFT)&0x8000)!=0);continue;}if(ha&&TranslateAcceleratorW(win,ha,&m))continue;TranslateMessage(&m);DispatchMessage(&m);if(scan_text&&!scan_active&&target==edit&&(dispatched==WM_KEYDOWN||dispatched==WM_KEYUP||dispatched==WM_LBUTTONDOWN||dispatched==WM_LBUTTONUP))publish_styles();}sedit_document_free(&doc);return(int)m.wParam;}
