#!/usr/bin/env node
/* mkgit2srclib.js — regenerate the two artifacts that let libgit2 build as a
 * gucman `srclib` package (ticket #473).
 *
 * A srclib package cannot carry compiler flags: `validateSrclibShape`
 * (os/os-common.js) accepts only `include` and `src`, and the shape is
 * enforced in mkpkg, foldPackages and gucman.c alike. The in-OS `cc` therefore
 * offers exactly ONE ambient header tier (/usr/local/include + /usr/include,
 * fed by the package's srclib.include dirs) and ONE require tier
 * (/usr/local/src + /usr/src). libgit2's own build, by contrast, wants nine
 * -I roots. This tool closes that gap by MATERIALIZING the -I search path as
 * files inside the tree:
 *
 *   1. FORWARDERS — for every (directory D, include name N) the build cannot
 *      resolve same-dir, a one-line D/N whose body is #include "<rel>/N",
 *      where <rel> reaches the search root that really owns N. Quote includes
 *      search the including file's own directory first, so the forwarder wins
 *      with no -I and no system-tier plant, in the host build and the in-OS
 *      build alike — ONE resolution path, not two.
 *
 *   2. include/git2_srclib.h — the __require_source block naming every
 *      translation unit of the library, so a consumer writes two #includes
 *      instead of maintaining ~190 require lines by hand (the libjpeg package
 *      makes its consumer carry that block; libgit2 is an order of magnitude
 *      bigger, so the package ships it).
 *
 * The forwarder set is derived from the COMPILER, not from a regex scan: the
 * tool builds vendor/libgit2/bin.json with the trimmed include list, reads the
 * "Could not find include file" diagnostics, emits forwarders, and repeats
 * until the build is clean. Only genuinely-reached includes get a forwarder —
 * an include inside an inactive #if never appears.
 *
 * Usage:
 *   node tools/mkgit2srclib.js            # regenerate both artifacts
 *   node tools/mkgit2srclib.js --check    # fail if git2_srclib.h is stale
 *
 * --check deliberately covers only git2_srclib.h, which must track bin.json's
 * source list and is cheap to verify. The forwarder set needs no separate
 * check: if one is missing, the ordinary `fakegit` / `projects` build fails,
 * because bin.json no longer passes the -I roots that used to hide the gap.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const V = path.join(ROOT, 'vendor/libgit2');
const BIN = path.join(V, 'bin.json');

/* The -I roots libgit2's build used before #473, minus `include` (which
 * survives as the package's srclib.include tier and as bin.json's one
 * remaining -I). Order is the search order: the porting layer at the tree root
 * shadows upstream (iterator.h), exactly as the old -I order did. */
const SEARCH_ROOTS = [
  'stubs', '.', 'src/util', 'src/libgit2',
  'deps/pcre2', 'deps/xdiff', 'deps/reftable', 'deps/zlib', 'stubs/netinet',
];

const FWD_MARK = 'c-compiler srclib forwarder (generated by tools/mkgit2srclib.js';

function isForwarder(p) {
  try { return fs.readFileSync(p, 'utf8').includes(FWD_MARK); } catch (e) { return false; }
}

function relFrom(dir, target) {
  const r = path.relative(path.join(V, dir), path.join(V, target));
  return r.split(path.sep).join('/');
}

/* Resolve NAME the way the pre-#473 build did: the first search root holding
 * it wins. Returns the tree-relative path, or null. */
function findInRoots(name) {
  for (const root of SEARCH_ROOTS) {
    const rel = path.normalize(path.join(root, name));
    if (rel.startsWith('..')) continue;
    try {
      if (fs.statSync(path.join(V, rel)).isFile()) return { rel: rel, root: root };
    } catch (e) { /* next */ }
  }
  return null;
}

/* A forwarder for a QUALIFIED name ("streams/socket.h") lands in a subdirectory
 * of the including file's own directory, so the body's relative path must be
 * computed from where the forwarder actually sits, not from `dir`. */
function writeForwarder(dir, name, target, root) {
  const relPath = path.join(dir, name);                 // tree-relative
  const out = path.join(V, relPath);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  const body = relFrom(path.dirname(relPath), target);
  fs.writeFileSync(out,
    '/* ' + FWD_MARK + ' — ticket #473).\n' +
    ' *\n' +
    ' * libgit2\'s own build resolved #include "' + name + '" through\n' +
    ' * -I ' + root + '. A gucman srclib package has no -I, so the tree\n' +
    ' * resolves it same-dir through this forwarder instead. Do not edit —\n' +
    ' * regenerate with `node tools/mkgit2srclib.js`.\n' +
    ' */\n' +
    '#include "' + body + '"\n');
  return out;
}

/* ---- pass 1: forwarders, driven by the compiler's own diagnostics ---- */
function generateForwarders() {
  const tmpOut = path.join(require('os').tmpdir(), 'mkgit2srclib-probe.wasm');
  const made = [];
  for (let pass = 1; pass <= 12; pass++) {
    const r = cp.spawnSync(process.execPath, [path.join(ROOT, 'compiler.js'), BIN, '-o', tmpOut],
      { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024, cwd: ROOT });
    const log = (r.stdout || '') + (r.stderr || '');
    if (r.status === 0) {
      console.log('pass ' + pass + ': build clean — ' + made.length + ' forwarder(s) generated');
      return made;
    }
    const missing = new Map();   // "dir\0name" -> true
    const re = /^(.*\.[ch]):\d+: error: Could not find include file: (.+)$/gm;
    let m;
    while ((m = re.exec(log))) {
      const file = m[1].startsWith('/') ? path.relative(V, m[1]) : m[1];
      if (file.startsWith('..')) continue;              // outside the tree
      missing.set(path.dirname(file) + '\0' + m[2].trim(), true);
    }
    if (!missing.size) {
      console.error('pass ' + pass + ': build failed with no missing-include diagnostics:\n' +
        log.split('\n').filter(l => l.includes('error')).slice(0, 20).join('\n'));
      process.exit(1);
    }
    let emitted = 0;
    for (const key of missing.keys()) {
      const [dir, name] = key.split('\0');
      const hit = findInRoots(name);
      if (!hit) {
        console.error('no search root owns ' + JSON.stringify(name) + ' (needed by ' + dir + ')');
        process.exit(1);
      }
      made.push(path.relative(ROOT, writeForwarder(dir, name, hit.rel, hit.root)));
      emitted++;
    }
    console.log('pass ' + pass + ': ' + emitted + ' forwarder(s)');
  }
  console.error('did not converge in 12 passes');
  process.exit(1);
}

/* ---- pass 2: the require block ---- */
function requireBlock() {
  const bin = JSON.parse(fs.readFileSync(BIN, 'utf8'));
  const tus = bin.sources.filter(s => s !== 'test_main.c').sort();
  return '/* git2_srclib.h — link libgit2 into a program built by the in-OS `cc`.\n' +
    ' *\n' +
    ' * Generated by tools/mkgit2srclib.js from vendor/libgit2/bin.json (#473).\n' +
    ' * Do not edit by hand; run `node tools/mkgit2srclib.js` after changing the\n' +
    ' * library\'s source list, and `--check` verifies the two agree.\n' +
    ' *\n' +
    ' * Usage — no -I, no explicit TU list:\n' +
    ' *\n' +
    ' *     #include <git2.h>\n' +
    ' *     #include <git2_srclib.h>\n' +
    ' *     int main(void) { git_libgit2_init(); ... }\n' +
    ' *\n' +
    ' * Each name below resolves through the srclib source tier: the `git2`\n' +
    ' * namespace is /usr/local/src/git2 when the package is installed by\n' +
    ' * gucman and /usr/src/git2 when it is folded into the image. The TUs pull\n' +
    ' * their own headers same-dir (see the generated forwarders), so nothing\n' +
    ' * here depends on which tier answered.\n' +
    ' *\n' +
    ' * libgit2 puts a 64 KiB GIT_BUFSIZE_FILEIO buffer on the stack in every\n' +
    ' * write path (lock_file), so the library raises the shadow stack to 1 MiB\n' +
    ' * with __minstack in missing_stubs.c. That is part of the TU set below —\n' +
    ' * a program that hand-picks TUs instead of including this header and\n' +
    ' * leaves missing_stubs.c out will underflow the default 64 KiB stack on\n' +
    ' * its first commit.\n' +
    ' */\n' +
    '\n#ifndef INCLUDE_git2_srclib_h__\n#define INCLUDE_git2_srclib_h__\n\n' +
    tus.map(t => '__require_source("git2/' + t + '");').join('\n') +
    '\n\n#endif\n';
}

const CHECK = process.argv.includes('--check');
const srclibH = path.join(V, 'include/git2_srclib.h');

if (CHECK) {
  let cur = null;
  try { cur = fs.readFileSync(srclibH, 'utf8'); } catch (e) { /* missing */ }
  const want = requireBlock();
  if (cur !== want) {
    console.error('vendor/libgit2/include/git2_srclib.h is stale — run: node tools/mkgit2srclib.js');
    process.exit(1);
  }
  console.log('git2_srclib.h is in sync with bin.json (' +
    (want.match(/__require_source/g) || []).length + ' translation units)');
  process.exit(0);
}

/* Drop stale forwarders first, so a removed include does not leave a file
 * behind that silently keeps resolving. Only our own generated files are
 * ever deleted — the marker comment is the identity. */
let dropped = 0;
(function sweep(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { sweep(p); try { fs.rmdirSync(p); } catch (x) { /* not empty */ } }
    else if (e.isFile() && isForwarder(p)) { fs.unlinkSync(p); dropped++; }
  }
})(V);
if (dropped) console.log('dropped ' + dropped + ' stale forwarder(s)');

generateForwarders();
fs.writeFileSync(srclibH, requireBlock());
console.log('wrote vendor/libgit2/include/git2_srclib.h');
