#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include <ctype.h>
#include <dirent.h>
#include "../../os/sedit/c_lex.h"
#include "../../os/sedit/document.h"
#include "../../os/sedit/styles.h"
#include "../../os/sha256.h"

static int fail;
#define OK(n,x) do{if(x)printf("ok %s\n",n);else{printf("FAIL %s\n",n);fail++;}}while(0)
/* Independent per-line run count for a token span (#728 oracle). */
static uint32_t ref_line_runs(const char*t,uint32_t a,uint32_t e){uint32_t n=0;while(a<e){uint32_t q=a;while(q<e&&t[q]!='\n')q++;if(q>a)n++;a=q<e?q+1:q;}return n;}
static uint64_t ref_runs_total(const SeditLexer*l,const char*t){uint64_t n=0;for(size_t i=0;i<l->token_count;i++)n+=ref_line_runs(t,l->tokens[i].start,l->tokens[i].end);return n;}
static int has(const SeditLexer*l,int k,const char*s,const char*src){for(size_t i=0;i<l->token_count;i++)if(l->tokens[i].kind==k&&l->tokens[i].end-l->tokens[i].start==strlen(s)&&!memcmp(src+l->tokens[i].start,s,strlen(s)))return 1;return 0;}
static int lex_equal(const SeditLexer*a,const SeditLexer*b){return a->token_count==b->token_count&&a->pair_count==b->pair_count&&!memcmp(a->tokens,b->tokens,a->token_count*sizeof(*a->tokens))&&!memcmp(a->pairs,b->pairs,a->pair_count*sizeof(*a->pairs));}
typedef struct { SeditToken t[4096]; size_t nt; SeditPair p[4096]; size_t np; } Ref;
static int ref_word(const char*s,size_t n,int*kind){static const char*ty[]={"auto","bool","char","const","double","enum","extern","float","inline","int","long","register","restrict","short","signed","static","struct","typedef","union","unsigned","void","volatile","_Atomic","_Bool","_Complex","_Imaginary",0};static const char*kw[]={"break","case","continue","default","do","else","for","goto","if","return","sizeof","switch","while","_Alignas","_Alignof","_Generic","_Noreturn","_Static_assert","_Thread_local",0};for(int i=0;ty[i];i++)if(strlen(ty[i])==n&&!memcmp(s,ty[i],n)){*kind=SEDIT_T_TYPE;return 1;}for(int i=0;kw[i];i++)if(strlen(kw[i])==n&&!memcmp(s,kw[i],n)){*kind=SEDIT_T_KEYWORD;return 1;}return 0;}
static void rt(Ref*r,size_t a,size_t b,int k){if(b>a&&r->nt<4096)r->t[r->nt++]=(SeditToken){(uint32_t)a,(uint32_t)b,(uint8_t)k};}
static int ropen(char c){return c=='('?')':c=='['?']':c=='{'?'}':0;}
static void ref_scan(const char*s,size_t n,Ref*r){memset(r,0,sizeof* r);struct{size_t at;char close;}st[1024];size_t ns=0;int bol=1;for(size_t i=0;i<n;){unsigned char c=s[i];if(c=='\n'){bol=1;i++;continue;}if(c==' '||c=='\t'||c=='\r'){i++;continue;}if(c=='#'&&bol){size_t a=i++;int esc=0;while(i<n){if(s[i]=='\\'){esc=!esc;i++;continue;}if(s[i]=='\n'&&!esc)break;esc=0;i++;}rt(r,a,i,SEDIT_T_PREPROCESSOR);continue;}bol=0;if(c=='/'&&i+1<n&&s[i+1]=='*'){size_t a=i;i+=2;while(i+1<n&&(s[i]!='*'||s[i+1]!='/'))i++;if(i+1<n)i+=2;rt(r,a,i,SEDIT_T_COMMENT);continue;}if(c=='/'&&i+1<n&&s[i+1]=='/'){size_t a=i;i+=2;while(i<n&&s[i]!='\n')i++;rt(r,a,i,SEDIT_T_COMMENT);continue;}if(c=='"'||c=='\''){char q=(char)c;size_t a=i++;int esc=0;while(i<n&&s[i]!='\n'){char z=s[i++];if(esc){esc=0;continue;}if(z=='\\'){esc=1;continue;}if(z==q)break;}rt(r,a,i,q=='"'?SEDIT_T_STRING:SEDIT_T_CHAR);continue;}if(isalpha(c)||c=='_'||c>=0x80){size_t a=i++;while(i<n&&((unsigned char)s[i]>=0x80||isalnum((unsigned char)s[i])||s[i]=='_'))i++;int k;if(ref_word(s+a,i-a,&k))rt(r,a,i,k);continue;}if(isdigit(c)||(c=='.'&&i+1<n&&isdigit((unsigned char)s[i+1]))){size_t a=i++;int exp=0;while(i<n){char z=s[i];if(isalnum((unsigned char)z)||z=='.'){exp=z=='e'||z=='E'||z=='p'||z=='P';i++;continue;}if((z=='+'||z=='-')&&exp){exp=0;i++;continue;}break;}rt(r,a,i,SEDIT_T_NUMBER);continue;}int close=ropen((char)c);if(close){if(ns<1024){st[ns].at=i;st[ns].close=(char)close;ns++;}rt(r,i,i+1,SEDIT_T_PUNCT);i++;continue;}if(c==')'||c==']'||c=='}'){if(ns&&st[ns-1].close==(char)c){size_t a=st[--ns].at;r->p[r->np++]=(SeditPair){(uint32_t)a,(uint32_t)i,0};r->p[r->np++]=(SeditPair){(uint32_t)i,(uint32_t)a,0};}else r->p[r->np++]=(SeditPair){(uint32_t)i,(uint32_t)i,1};rt(r,i,i+1,SEDIT_T_PUNCT);i++;continue;}i++;}while(ns){size_t a=st[--ns].at;r->p[r->np++]=(SeditPair){(uint32_t)a,(uint32_t)a,1};}}
/* Deliberately defective scanner: it has no BLOCK_COMMENT state, so braces
 * and words inside a block comment are treated as live source. */
static void broken_scan_no_block_comments(const char*s,size_t n,Ref*r){memset(r,0,sizeof* r);struct{size_t at;char close;}st[1024];size_t ns=0;for(size_t i=0;i<n;){unsigned char c=s[i];if(c=='"'||c=='\''){char q=(char)c;size_t a=i++;int esc=0;while(i<n&&s[i]!='\n'){char z=s[i++];if(esc){esc=0;continue;}if(z=='\\'){esc=1;continue;}if(z==q)break;}rt(r,a,i,q=='"'?SEDIT_T_STRING:SEDIT_T_CHAR);continue;}if(isalpha(c)||c=='_'||c>=0x80){size_t a=i++;while(i<n&&((unsigned char)s[i]>=0x80||isalnum((unsigned char)s[i])||s[i]=='_'))i++;int k;if(ref_word(s+a,i-a,&k))rt(r,a,i,k);continue;}int close=ropen((char)c);if(close){st[ns].at=i;st[ns].close=(char)close;ns++;rt(r,i,i+1,SEDIT_T_PUNCT);i++;continue;}if(c==')'||c==']'||c=='}'){if(ns&&st[ns-1].close==(char)c){size_t a=st[--ns].at;r->p[r->np++]=(SeditPair){(uint32_t)a,(uint32_t)i,0};r->p[r->np++]=(SeditPair){(uint32_t)i,(uint32_t)a,0};}else r->p[r->np++]=(SeditPair){(uint32_t)i,(uint32_t)i,1};rt(r,i,i+1,SEDIT_T_PUNCT);i++;continue;}i++;}while(ns){size_t a=st[--ns].at;r->p[r->np++]=(SeditPair){(uint32_t)a,(uint32_t)a,1};}}
static int lex_ref_equal(const SeditLexer*l,const Ref*r){return l->token_count==r->nt&&l->pair_count==r->np&&!memcmp(l->tokens,r->t,r->nt*sizeof*r->t)&&!memcmp(l->pairs,r->p,r->np*sizeof*r->p);}
/* Injected turn clock (#729): counts calls, steps a fixed amount per call. */
typedef struct { long long t, step; int calls; } FakeClock;
static long long fake_now(void*p){FakeClock*c=(FakeClock*)p;c->calls++;long long v=c->t;c->t+=c->step;return v;}
static int check_all_splits(const char*s,size_t n,const Ref*r){for(size_t cut=0;cut<=n;cut++){SeditLexer q;sedit_lex_init(&q);int ok=sedit_lex_feed(&q,s,cut)&&sedit_lex_feed(&q,s+cut,n-cut)&&sedit_lex_finish(&q)&&lex_ref_equal(&q,r);sedit_lex_free(&q);if(!ok)return 0;}return 1;}
#ifdef SEDIT_TEST
static int fault,eintr_once,unlinks,stat_calls,hash_calls;
static int t_open(const char*p,int f,mode_t m){if(fault==1&&(f&O_WRONLY)){errno=ENOSPC;return-1;}return open(p,f,m);}
static ssize_t t_write(int fd,const void*b,size_t n){if(fault==2||fault==10){errno=ENOSPC;return-1;}if(fault==3&&eintr_once++==0){errno=EINTR;return-1;}if(fault==4&&n>1)n=1;return write(fd,b,n);}
static int t_chmod(int fd,mode_t m){if(fault==5){errno=EPERM;return-1;}return fchmod(fd,m);}
static int t_fsync(int fd){if(fault==6){errno=ENOSPC;return-1;}return fsync(fd);}
static int t_close(int fd){int r=close(fd);if(fault==7){errno=EIO;return-1;}return r;}
static int t_rename(const char*a,const char*b){if(fault==8){errno=EACCES;return-1;}return rename(a,b);}
static int t_unlink(const char*p){unlinks++;if(fault==10){errno=EACCES;return-1;}return unlink(p);}
static int t_stat(const char*p,struct stat*s){stat_calls++;if(fault==11&&stat_calls>=2){errno=EIO;return-1;}return stat(p,s);}
static int t_sha(const char*p,char h[65]){hash_calls++;if(fault==9||(fault==12&&hash_calls>=2)){errno=EIO;return-1;}return sha256_path(p,h);}
static void set_fault(int f){SeditIOOps o={0};fault=f;eintr_once=0;unlinks=0;stat_calls=hash_calls=0;o.stat_fn=t_stat;o.open_fn=t_open;o.write_fn=t_write;o.fchmod_fn=t_chmod;o.fsync_fn=t_fsync;o.close_fn=t_close;o.rename_fn=t_rename;o.unlink_fn=t_unlink;o.sha256_path_fn=t_sha;sedit_document_test_io(&o);}
static int exact_file(const char*p,const char*s,size_t n){char b[64];FILE*f=fopen(p,"rb");if(!f)return 0;size_t z=fread(b,1,sizeof b,f);fclose(f);return z==n&&!memcmp(b,s,n);}
static int temp_count(const char*dir){DIR*d=opendir(dir);if(!d)return-1;int n=0;struct dirent*e;while((e=readdir(d)))if(strstr(e->d_name,".sedit.")&&strstr(e->d_name,".tmp"))n++;closedir(d);return n;}
#endif
int main(int argc,char**argv){
 const char*src="#define OPEN { \\\n+  1\nint main(void) { /* } */ const char *s=\"{\"; return (2); }\n/* unterminated";
 SeditLexer l;sedit_lex_init(&l);OK("chunk1",sedit_lex_feed(&l,src,25));OK("chunk2",sedit_lex_feed(&l,src+25,strlen(src)-25));OK("finish",sedit_lex_finish(&l));OK("keyword",has(&l,SEDIT_T_KEYWORD,"return",src));OK("type",has(&l,SEDIT_T_TYPE,"int",src));OK("comment",has(&l,SEDIT_T_COMMENT,"/* } */",src));uint32_t m;int u;const char*brace=strstr(src,"main(void) {")+11;OK("normal brace paired",sedit_pair_mate(&l,(uint32_t)(brace-src),&m,&u)&&!u);OK("comment brace excluded",!sedit_pair_mate(&l,(uint32_t)(strstr(src,"/* } */")-src+3),&m,&u));sedit_lex_free(&l);
 const char*boundary="int café=.12; /* split */ return (café); // tail\n";Ref bref;ref_scan(boundary,strlen(boundary),&bref);SeditLexer whole;sedit_lex_init(&whole);sedit_lex_feed(&whole,boundary,strlen(boundary));sedit_lex_finish(&whole);OK("independent reference agrees on readable witness",lex_ref_equal(&whole,&bref));OK("every split boundary is invisible",check_all_splits(boundary,strlen(boundary),&bref));OK("split witness keyword",has(&whole,SEDIT_T_KEYWORD,"return",boundary));OK("split witness block comment",has(&whole,SEDIT_T_COMMENT,"/* split */",boundary));sedit_lex_free(&whole);
 char random_src[8192];size_t rw=0;const char*atoms[]={"int ","x=.5;","/* [ ] */","return ","(x);","// }\n","\"{utf8-é}\";","#define Q(x) \\\n (x)\n"};unsigned seed=718;for(int ri=0;ri<200;ri++){seed=seed*1664525u+1013904223u;const char*a0=atoms[seed%8];size_t an=strlen(a0);if(rw+an<sizeof random_src){memcpy(random_src+rw,a0,an);rw+=an;}}SeditLexer oracle;sedit_lex_init(&oracle);sedit_lex_feed(&oracle,random_src,rw);sedit_lex_finish(&oracle);int random_ok=1;for(int trial=0;trial<64;trial++){SeditLexer q;sedit_lex_init(&q);size_t at=0;while(at<rw){seed=seed*1664525u+1013904223u;size_t z=1+seed%47;if(z>rw-at)z=rw-at;if(!sedit_lex_feed(&q,random_src+at,z))random_ok=0;at+=z;}if(!sedit_lex_finish(&q)||!lex_equal(&oracle,&q))random_ok=0;sedit_lex_free(&q);}OK("randomized split schedules equal independent one-feed oracle",random_ok);sedit_lex_free(&oracle);
 Ref random_ref;ref_scan(random_src,rw,&random_ref);int independent_random=1;for(int trial=0;trial<64;trial++){SeditLexer q;sedit_lex_init(&q);size_t at=0;while(at<rw){seed=seed*1664525u+1013904223u;size_t z=1+seed%47;if(z>rw-at)z=rw-at;sedit_lex_feed(&q,random_src+at,z);at+=z;}sedit_lex_finish(&q);if(!lex_ref_equal(&q,&random_ref))independent_random=0;sedit_lex_free(&q);}OK("every randomized completed scan matches independent token and pair maps",independent_random);
 const char*fixed="int f(){/* } */return \"{\";}";Ref fixed_expected={.t={{0,3,SEDIT_T_TYPE},{5,6,SEDIT_T_PUNCT},{6,7,SEDIT_T_PUNCT},{7,8,SEDIT_T_PUNCT},{8,15,SEDIT_T_COMMENT},{15,21,SEDIT_T_KEYWORD},{22,25,SEDIT_T_STRING},{26,27,SEDIT_T_PUNCT}},.nt=8,.p={{5,6,0},{6,5,0},{7,26,0},{26,7,0}},.np=4};Ref fixed_ref,broken;ref_scan(fixed,strlen(fixed),&fixed_ref);broken_scan_no_block_comments(fixed,strlen(fixed),&broken);SeditLexer fixed_prod;sedit_lex_init(&fixed_prod);sedit_lex_feed(&fixed_prod,fixed,strlen(fixed));sedit_lex_finish(&fixed_prod);OK("fixed independently encoded comment/string spans and delimiter pairs",lex_ref_equal(&fixed_prod,&fixed_expected)&&!memcmp(&fixed_ref,&fixed_expected,sizeof fixed_ref));OK("broken scanner without BLOCK_COMMENT state is discriminating",!lex_ref_equal(&fixed_prod,&broken)&&memcmp(&broken,&fixed_expected,sizeof broken));sedit_lex_free(&fixed_prod);
 rw=0;memcpy(random_src,"int x=1+2;\n",11);rw=11;int edit_ok=1;for(int step=0;step<80;step++){seed=seed*1664525u+1013904223u;size_t at=rw?seed%(rw+1):0;seed=seed*1664525u+1013904223u;int op=seed%5;if((op==1||op==2)&&rw){size_t del=1+seed%5;if(at==rw)at--;if(del>rw-at)del=rw-at;memmove(random_src+at,random_src+at+del,rw-at-del);rw-=del;}if(op!=1){const char*a0=atoms[(seed>>8)%8];size_t an=strlen(a0);if(op==3&&an>1)an/=2;if(rw+an<sizeof random_src){memmove(random_src+at+an,random_src+at,rw-at);memcpy(random_src+at,a0,an);rw+=an;}}Ref rr;ref_scan(random_src,rw,&rr);SeditLexer q;sedit_lex_init(&q);sedit_lex_feed(&q,random_src,rw);sedit_lex_finish(&q);if(!lex_ref_equal(&q,&rr)||!check_all_splits(random_src,rw,&rr))edit_ok=0;sedit_lex_free(&q);}OK("seeded insert delete replace split join edits match independent scanner after every edit and feed split",edit_ok);
 const char*num="1+2 1e+2 0x1p-3";Ref nr;ref_scan(num,strlen(num),&nr);SeditLexer nl;sedit_lex_init(&nl);sedit_lex_feed(&nl,num,strlen(num));sedit_lex_finish(&nl);OK("pp-number signs only follow exponent markers",lex_ref_equal(&nl,&nr)&&nl.token_count==4);sedit_lex_free(&nl);
 char p[1024];uint32_t line;OK("arg location",!sedit_document_location("colon:name.c:42",p,sizeof p,&line)&&!strcmp(p,"colon:name.c")&&line==42);OK("primary diagnostic",!sedit_document_diagnostic("colon:name.c:9: error: bad",p,sizeof p,&line)&&line==9);OK("link diagnostic",!sedit_document_diagnostic("  at colon:name.c:7",p,sizeof p,&line)&&line==7);OK("reject column",sedit_document_diagnostic("a.c:2:3: error: bad",p,sizeof p,&line)!=0);
 OK("reject zero line",sedit_document_location("a.c:0",p,sizeof p,&line)!=0);OK("reject overflow line",sedit_document_location("a.c:4294967296",p,sizeof p,&line)!=0);OK("reject multiline diagnostic",sedit_document_diagnostic("a.c:2: error: x\nmore",p,sizeof p,&line)!=0);OK("reject unrelated text",sedit_document_diagnostic("a.c:2: note: x",p,sizeof p,&line)!=0);
 uint32_t selection=2,navigation=3,visible_lines=0;const char*grown="one\ntwo\nthree\nfour";OK("immediate post-change growth accepts line from authoritative snapshot",!sedit_navigation_apply(grown,strlen(grown),4,&selection,&navigation,&visible_lines)&&selection==14&&navigation==4&&visible_lines==4);selection=14;navigation=4;OK("immediate post-change shrink rejects removed line",sedit_navigation_apply("one",3,4,&selection,&navigation,&visible_lines)!=0);OK("navigation rejection preserves selection and status state",selection==14&&navigation==4&&visible_lines==1);
 /* #728: the style batch is written per LINE RUN; sizing it per token
  * overflows the heap the moment one token spans many lines (unterminated
  * block comment = ordinary typing). The batch must satisfy the consumer's
  * own independent validator and carry exactly one entry per line run. */
 {size_t bcap=64*1024,bn=0;char*bsrc=malloc(bcap);bn+=(size_t)snprintf(bsrc+bn,bcap-bn,"int head(void){return 0;}\n/*\n");for(int ln=0;ln<500;ln++)bn+=(size_t)snprintf(bsrc+bn,bcap-bn,"  comment line %d with words\n",ln);
  SeditLexer sl;sedit_lex_init(&sl);sedit_lex_feed(&sl,bsrc,bn);sedit_lex_finish(&sl);uint64_t runs=ref_runs_total(&sl,bsrc);int tr=-1;
  GUCEDIT_BATCH_V1*bb=sedit_styles_build(&sl,bsrc,bn,0,42,&tr);
  OK("unterminated block comment batch built",bb!=NULL&&runs>500);
  OK("unterminated block comment batch is one entry per line run and validator-clean",bb&&tr==0&&bb->count==runs&&gucedit_check_batch(bb,bsrc,(uint32_t)bn,42)==GUCEDIT_CHECK_OK);
  free(bb);sedit_lex_free(&sl);free(bsrc);}
 {const char*s2="int f(){}\n";SeditLexer s2l;sedit_lex_init(&s2l);sedit_lex_feed(&s2l,s2,strlen(s2));sedit_lex_finish(&s2l);int tr=-1;
  GUCEDIT_BATCH_V1*bb=sedit_styles_build(&s2l,s2,strlen(s2),5,7,&tr);
  int boxes=0;if(bb)for(uint32_t i=0;i<bb->count;i++)if(bb->styles[i].flags&GUES_BOX)boxes++;
  OK("caret delimiter mate boxes survive in a validator-clean batch",bb&&tr==0&&boxes==2&&gucedit_check_batch(bb,s2,(uint32_t)strlen(s2),7)==GUCEDIT_CHECK_OK);
  free(bb);sedit_lex_free(&s2l);}
 OK("repo header path supplied",argc>=3);
 if(argc>=3){FILE*hf=fopen(argv[2],"rb");OK("repo header opens",hf!=NULL);if(hf){fseek(hf,0,SEEK_END);long hn=ftell(hf);fseek(hf,0,SEEK_SET);char*hs=malloc((size_t)hn);size_t got=fread(hs,1,(size_t)hn,hf);fclose(hf);
  SeditLexer hl;sedit_lex_init(&hl);sedit_lex_feed(&hl,hs,got);sedit_lex_finish(&hl);uint64_t runs=ref_runs_total(&hl,hs);int tr=-1;
  GUCEDIT_BATCH_V1*bb=sedit_styles_build(&hl,hs,got,0,9,&tr);
  OK("repo header batch built",bb!=NULL&&got>100000&&runs>10000);
  OK("repo header batch is one entry per line run and validator-clean",bb&&tr==0&&bb->count==runs&&gucedit_check_batch(bb,hs,(uint32_t)got,9)==GUCEDIT_CHECK_OK);
  free(bb);sedit_lex_free(&hl);free(hs);}}
 {size_t rn=(size_t)GUCEDIT_MAX_STYLES+100000;size_t tn=3+2*rn;char*ts=malloc(tn);ts[0]='/';ts[1]='*';ts[2]='\n';for(size_t i=0;i<rn;i++){ts[3+2*i]='x';ts[4+2*i]='\n';}
  SeditLexer tl;sedit_lex_init(&tl);sedit_lex_feed(&tl,ts,tn);sedit_lex_finish(&tl);int tr=-1;
  GUCEDIT_BATCH_V1*bb=sedit_styles_build(&tl,ts,tn,0,11,&tr);
  OK("over-limit batch built",bb!=NULL);
  OK("over-limit batch truncates honestly at the ABI style cap",bb&&tr==1&&bb->count==GUCEDIT_MAX_STYLES&&gucedit_check_batch(bb,ts,(uint32_t)tn,11)==GUCEDIT_CHECK_OK);
  free(bb);sedit_lex_free(&tl);free(ts);}
 { /* #729: the incremental-scan turn policy executes — byte cap, chunk
    * granularity, time cap, and chunked-turn equality with a one-feed
    * oracle. The turn clock is injected; production passes CLOCK_MONOTONIC. */
  const char pat[]="int a=1;/* c */return(b);// zzz\n";size_t pn=strlen(pat);
  size_t big_n=(size_t)SEDIT_SCAN_TURN_BYTES*4;char*big=malloc(big_n);
  for(size_t i=0;i<big_n;i+=pn)memcpy(big+i,pat,pn<=big_n-i?pn:big_n-i);
  FakeClock ck={0,0,0};SeditLexer sl;sedit_lex_init(&sl);size_t off=0;int turns=0,r0,cap_ok=1,calls_turn1=0;
  while((r0=sedit_scan_turn(&sl,big,big_n,&off,fake_now,&ck))==SEDIT_SCAN_MORE){turns++;if(turns==1)calls_turn1=ck.calls;if(off!=(size_t)turns*SEDIT_SCAN_TURN_BYTES)cap_ok=0;if(turns>16)break;}
  turns++;
  OK("scan turn stops at the byte cap",cap_ok&&turns==4&&off==big_n&&r0==SEDIT_SCAN_DONE);
  /* begun + one clock read per chunk, except the last: the byte-cap term
   * short-circuits the condition before the clock on the capped chunk. */
  OK("scan turn feeds in chunk-size steps",calls_turn1==(int)(SEDIT_SCAN_TURN_BYTES/SEDIT_SCAN_CHUNK));
  OK("scan turns finish",sedit_lex_finish(&sl)!=0);
  SeditLexer one;sedit_lex_init(&one);sedit_lex_feed(&one,big,big_n);sedit_lex_finish(&one);
  OK("chunked turns equal the one-feed oracle",lex_equal(&one,&sl));
  sedit_lex_free(&one);sedit_lex_free(&sl);
  FakeClock slow={0,SEDIT_SCAN_TURN_NS+1,0};SeditLexer s2;sedit_lex_init(&s2);size_t off2=0;
  OK("scan turn yields on the time cap after one chunk",sedit_scan_turn(&s2,big,big_n,&off2,fake_now,&slow)==SEDIT_SCAN_MORE&&off2==SEDIT_SCAN_CHUNK);
  sedit_lex_free(&s2);free(big);}
 if(argc<2)return 2;char f[1024],f2[1024],linkp[1024],hard[1024];snprintf(f,sizeof f,"%s/a.c",argv[1]);snprintf(f2,sizeof f2,"%s/b.c",argv[1]);snprintf(linkp,sizeof linkp,"%s/l.c",argv[1]);snprintf(hard,sizeof hard,"%s/h.c",argv[1]);FILE*fp=fopen(f,"wb");fwrite("a\r\nb\r\n",1,6,fp);fclose(fp);symlink("a.c",linkp);SeditDocument d;sedit_document_init(&d);OK("load symlink",!sedit_document_load(&d,linkp));OK("CRLF detected",d.eol==SEDIT_EOL_CRLF);OK("physical target",strstr(d.target_path,"/a.c")!=NULL);OK("atomic save",sedit_document_save(&d,NULL,"a\nbb\n",5,0,0)==SEDIT_SAVE_OK);char b[32]={0};fp=fopen(f,"rb");size_t n=fread(b,1,sizeof b,fp);fclose(fp);OK("CRLF preserved",n==7&&!memcmp(b,"a\r\nbb\r\n",7));OK("symlink preserved",lstat(linkp,&d.opened_stat)==0&&S_ISLNK(d.opened_stat.st_mode));
 stat(f,&d.opened_stat);fp=fopen(f2,"wb");fwrite("other",1,5,fp);fclose(fp);unlink(linkp);symlink("b.c",linkp);OK("symlink retarget is conflict",sedit_document_save(&d,NULL,"mine",4,0,0)==SEDIT_SAVE_CONFLICT);memset(b,0,sizeof b);fp=fopen(f,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Cancel preserves old physical target",n==7&&!memcmp(b,"a\r\nbb\r\n",7));fp=fopen(f2,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Cancel preserves current physical target",n==5&&!memcmp(b,"other",5));struct stat link_before,b_before;stat(f2,&b_before);lstat(linkp,&link_before);OK("Overwrite publishes to currently resolved target",sedit_document_save(&d,NULL,"mine",4,1,0)==SEDIT_SAVE_OK&&strstr(d.target_path,"/b.c")!=NULL);struct stat link_after,b_after;lstat(linkp,&link_after);stat(f2,&b_after);OK("Overwrite preserves symlink and replaces current target inode",S_ISLNK(link_after.st_mode)&&b_before.st_ino!=b_after.st_ino);fp=fopen(f,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Overwrite leaves former target exact",n==7&&!memcmp(b,"a\r\nbb\r\n",7));char saveas[1024];snprintf(saveas,sizeof saveas,"%s/save-as.c",argv[1]);OK("Save As publishes only chosen path",sedit_document_save(&d,saveas,"copy",4,0,0)==SEDIT_SAVE_OK);fp=fopen(f2,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Save As leaves symlink target exact",n==4&&!memcmp(b,"mine",4));lstat(linkp,&link_after);OK("Save As leaves symlink intact",S_ISLNK(link_after.st_mode));unlink(linkp);symlink("a.c",linkp);sedit_document_free(&d);sedit_document_init(&d);OK("reload original lane for fault tests",!sedit_document_load(&d,linkp));
#ifdef SEDIT_TEST
 set_fault(3);OK("write EINTR is retried",sedit_document_save(&d,NULL,"a\nbb\n",5,0,0)==SEDIT_SAVE_OK);set_fault(4);OK("short writes complete",sedit_document_save(&d,NULL,"a\nbb\n",5,0,0)==SEDIT_SAVE_OK);int stages[]={1,2,5,6,7,8,9,10};const char*names[]={"create ENOSPC","write ENOSPC","chmod failure","fsync failure","close failure","rename failure","preflight hash failure","unlink cleanup failure"};const char*ops[]={"create temp","write temp","chmod temp","fsync temp","close temp","rename temp","hash current file","write temp"};for(size_t si=0;si<sizeof stages/sizeof stages[0];si++){set_fault(stages[si]);d.dirty=1;OK(names[si],sedit_document_save(&d,NULL,"changed",7,0,0)==SEDIT_SAVE_ERROR);OK("failed save retains dirty state",d.dirty==1);OK("failed save retains exact operation",strstr(d.error,ops[si])!=NULL);OK("failed save leaves original bytes exact",exact_file(f,"a\r\nbb\r\n",7));if(stages[si]==10)OK("unlink failure retains temp and reports primary plus cleanup",unlinks==1&&temp_count(argv[1])==1&&strstr(d.error,"write temp")&&strstr(d.error,"cleanup unlink")&&strstr(d.error,"Permission denied"));else OK("failed save leaves no temp",temp_count(argv[1])==0);}sedit_document_test_io(NULL);
 char retained[1200];snprintf(retained,sizeof retained,"%s.sedit.%ld.0.tmp",f,(long)getpid());unlink(retained);sedit_document_test_io(NULL);sedit_document_free(&d);sedit_document_init(&d);OK("reload before post-publication faults",!sedit_document_load(&d,f));set_fault(11);d.dirty=1;struct stat before_pub;stat(f,&before_pub);OK("post-rename stat has distinct published result",sedit_document_save(&d,NULL,"stat-published",14,0,0)==SEDIT_SAVE_PUBLISHED_REFRESH_FAILED);struct stat after_pub;stat(f,&after_pub);OK("stat refresh failure admits published bytes and invalid identity",exact_file(f,"stat-published",14)&&before_pub.st_ino!=after_pub.st_ino&&!d.have_snapshot&&d.dirty&&strstr(d.error,"refresh stat after publication"));sedit_document_test_io(NULL);fp=fopen(f,"wb");fwrite("external-after-stat",1,19,fp);fclose(fp);OK("ordinary retry with invalid identity demands explicit disposition",sedit_document_save(&d,NULL,"retry-must-not-publish",22,0,0)==SEDIT_SAVE_CONFLICT);OK("ordinary retry preserves external bytes",exact_file(f,"external-after-stat",19));OK("explicit Overwrite after invalid identity publishes and refreshes",sedit_document_save(&d,NULL,"explicit-overwrite",18,1,0)==SEDIT_SAVE_OK&&exact_file(f,"explicit-overwrite",18)&&d.have_snapshot&&!d.dirty);
 set_fault(12);d.dirty=1;OK("post-rename hash has distinct published result",sedit_document_save(&d,NULL,"hash-published",14,0,0)==SEDIT_SAVE_PUBLISHED_REFRESH_FAILED);OK("hash refresh failure admits published bytes and invalid identity",exact_file(f,"hash-published",14)&&!d.have_snapshot&&d.dirty&&strstr(d.error,"refresh hash after publication"));sedit_document_test_io(NULL);fp=fopen(f,"wb");fwrite("external-after-hash",1,19,fp);fclose(fp);char recovery_saveas[1024];snprintf(recovery_saveas,sizeof recovery_saveas,"%s/recovered-save-as.c",argv[1]);OK("Save As after invalid identity publishes and refreshes",sedit_document_save(&d,recovery_saveas,"explicit-save-as",16,0,0)==SEDIT_SAVE_OK&&exact_file(recovery_saveas,"explicit-save-as",16)&&d.have_snapshot&&!d.dirty);OK("Save As preserves externally rewritten original",exact_file(f,"external-after-hash",19));sedit_document_free(&d);sedit_document_init(&d);OK("reload after publication faults",!sedit_document_load(&d,f));
#endif
 fp=fopen(f,"wb");fwrite("external",1,8,fp);fclose(fp);OK("hash conflict",sedit_document_save(&d,NULL,"mine",4,0,0)==SEDIT_SAVE_CONFLICT);sedit_document_free(&d);sedit_document_init(&d);OK("reload",!sedit_document_load(&d,f));link(f,hard);OK("hardlink refusal",sedit_document_save(&d,NULL,"new",3,0,0)==SEDIT_SAVE_HARDLINK);OK("explicit break",sedit_document_save(&d,NULL,"new",3,0,1)==SEDIT_SAVE_OK);struct stat a,h;stat(f,&a);stat(hard,&h);OK("break retained peer",a.st_ino!=h.st_ino);sedit_document_free(&d);
 fp=fopen(f2,"wb");fwrite("\xef\xbb\xbf" "a\r\nb\rc\nz",1,11,fp);fclose(fp);sedit_document_init(&d);OK("mixed EOL plus BOM loads",!sedit_document_load(&d,f2)&&d.eol==SEDIT_EOL_MIXED&&d.bom);OK("explicit EOL choice",!sedit_document_set_eol(&d,SEDIT_EOL_CR));OK("BOM and no-final-newline save",sedit_document_save(&d,NULL,d.text,d.len,0,0)==SEDIT_SAVE_OK);memset(b,0,sizeof b);fp=fopen(f2,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("chosen CR encoding exact",n==10&&!memcmp(b,"\xef\xbb\xbf" "a\rb\rc\rz",10));sedit_document_free(&d);
 return fail?1:0;
}
