#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include <ctype.h>
#include <dirent.h>
#include "../../os/sedit/c_lex.h"
#include "../../os/sedit/document.h"
#include "../../os/sha256.h"

static int fail;
#define OK(n,x) do{if(x)printf("ok %s\n",n);else{printf("FAIL %s\n",n);fail++;}}while(0)
static int has(const SeditLexer*l,int k,const char*s,const char*src){for(size_t i=0;i<l->token_count;i++)if(l->tokens[i].kind==k&&l->tokens[i].end-l->tokens[i].start==strlen(s)&&!memcmp(src+l->tokens[i].start,s,strlen(s)))return 1;return 0;}
static int lex_equal(const SeditLexer*a,const SeditLexer*b){return a->token_count==b->token_count&&a->pair_count==b->pair_count&&!memcmp(a->tokens,b->tokens,a->token_count*sizeof(*a->tokens))&&!memcmp(a->pairs,b->pairs,a->pair_count*sizeof(*a->pairs));}
typedef struct { SeditToken t[4096]; size_t nt; SeditPair p[4096]; size_t np; } Ref;
static int ref_word(const char*s,size_t n,int*kind){static const char*ty[]={"auto","bool","char","const","double","enum","extern","float","inline","int","long","register","restrict","short","signed","static","struct","typedef","union","unsigned","void","volatile","_Atomic","_Bool","_Complex","_Imaginary",0};static const char*kw[]={"break","case","continue","default","do","else","for","goto","if","return","sizeof","switch","while","_Alignas","_Alignof","_Generic","_Noreturn","_Static_assert","_Thread_local",0};for(int i=0;ty[i];i++)if(strlen(ty[i])==n&&!memcmp(s,ty[i],n)){*kind=SEDIT_T_TYPE;return 1;}for(int i=0;kw[i];i++)if(strlen(kw[i])==n&&!memcmp(s,kw[i],n)){*kind=SEDIT_T_KEYWORD;return 1;}return 0;}
static void rt(Ref*r,size_t a,size_t b,int k){if(b>a&&r->nt<4096)r->t[r->nt++]=(SeditToken){(uint32_t)a,(uint32_t)b,(uint8_t)k};}
static int ropen(char c){return c=='('?')':c=='['?']':c=='{'?'}':0;}
static void ref_scan(const char*s,size_t n,Ref*r){memset(r,0,sizeof* r);struct{size_t at;char close;}st[1024];size_t ns=0;int bol=1;for(size_t i=0;i<n;){unsigned char c=s[i];if(c=='\n'){bol=1;i++;continue;}if(c==' '||c=='\t'||c=='\r'){i++;continue;}if(c=='#'&&bol){size_t a=i++;int esc=0;while(i<n){if(s[i]=='\\'){esc=!esc;i++;continue;}if(s[i]=='\n'&&!esc)break;esc=0;i++;}rt(r,a,i,SEDIT_T_PREPROCESSOR);continue;}bol=0;if(c=='/'&&i+1<n&&s[i+1]=='*'){size_t a=i;i+=2;while(i+1<n&&(s[i]!='*'||s[i+1]!='/'))i++;if(i+1<n)i+=2;rt(r,a,i,SEDIT_T_COMMENT);continue;}if(c=='/'&&i+1<n&&s[i+1]=='/'){size_t a=i;i+=2;while(i<n&&s[i]!='\n')i++;rt(r,a,i,SEDIT_T_COMMENT);continue;}if(c=='"'||c=='\''){char q=(char)c;size_t a=i++;int esc=0;while(i<n&&s[i]!='\n'){char z=s[i++];if(esc){esc=0;continue;}if(z=='\\'){esc=1;continue;}if(z==q)break;}rt(r,a,i,q=='"'?SEDIT_T_STRING:SEDIT_T_CHAR);continue;}if(isalpha(c)||c=='_'||c>=0x80){size_t a=i++;while(i<n&&((unsigned char)s[i]>=0x80||isalnum((unsigned char)s[i])||s[i]=='_'))i++;int k;if(ref_word(s+a,i-a,&k))rt(r,a,i,k);continue;}if(isdigit(c)||(c=='.'&&i+1<n&&isdigit((unsigned char)s[i+1]))){size_t a=i++;int exp=0;while(i<n){char z=s[i];if(isalnum((unsigned char)z)||z=='.'){exp=z=='e'||z=='E'||z=='p'||z=='P';i++;continue;}if((z=='+'||z=='-')&&exp){exp=0;i++;continue;}break;}rt(r,a,i,SEDIT_T_NUMBER);continue;}int close=ropen((char)c);if(close){if(ns<1024){st[ns].at=i;st[ns].close=(char)close;ns++;}rt(r,i,i+1,SEDIT_T_PUNCT);i++;continue;}if(c==')'||c==']'||c=='}'){if(ns&&st[ns-1].close==(char)c){size_t a=st[--ns].at;r->p[r->np++]=(SeditPair){(uint32_t)a,(uint32_t)i,0};r->p[r->np++]=(SeditPair){(uint32_t)i,(uint32_t)a,0};}else r->p[r->np++]=(SeditPair){(uint32_t)i,(uint32_t)i,1};rt(r,i,i+1,SEDIT_T_PUNCT);i++;continue;}i++;}while(ns){size_t a=st[--ns].at;r->p[r->np++]=(SeditPair){(uint32_t)a,(uint32_t)a,1};}}
static int lex_ref_equal(const SeditLexer*l,const Ref*r){return l->token_count==r->nt&&l->pair_count==r->np&&!memcmp(l->tokens,r->t,r->nt*sizeof*r->t)&&!memcmp(l->pairs,r->p,r->np*sizeof*r->p);}
static int check_all_splits(const char*s,size_t n,const Ref*r){for(size_t cut=0;cut<=n;cut++){SeditLexer q;sedit_lex_init(&q);int ok=sedit_lex_feed(&q,s,cut)&&sedit_lex_feed(&q,s+cut,n-cut)&&sedit_lex_finish(&q)&&lex_ref_equal(&q,r);sedit_lex_free(&q);if(!ok)return 0;}return 1;}
#ifdef SEDIT_TEST
static int fault,eintr_once,unlinks;
static int t_open(const char*p,int f,mode_t m){if(fault==1&&(f&O_WRONLY)){errno=ENOSPC;return-1;}return open(p,f,m);}
static ssize_t t_write(int fd,const void*b,size_t n){if(fault==2||fault==10){errno=ENOSPC;return-1;}if(fault==3&&eintr_once++==0){errno=EINTR;return-1;}if(fault==4&&n>1)n=1;return write(fd,b,n);}
static int t_chmod(int fd,mode_t m){if(fault==5){errno=EPERM;return-1;}return fchmod(fd,m);}
static int t_fsync(int fd){if(fault==6){errno=ENOSPC;return-1;}return fsync(fd);}
static int t_close(int fd){int r=close(fd);if(fault==7){errno=EIO;return-1;}return r;}
static int t_rename(const char*a,const char*b){if(fault==8){errno=EACCES;return-1;}return rename(a,b);}
static int t_unlink(const char*p){unlinks++;if(fault==10){errno=EACCES;return-1;}return unlink(p);}
static int t_sha(const char*p,char h[65]){if(fault==9){errno=EIO;return-1;}return sha256_path(p,h);}
static void set_fault(int f){SeditIOOps o={0};fault=f;eintr_once=0;unlinks=0;o.open_fn=t_open;o.write_fn=t_write;o.fchmod_fn=t_chmod;o.fsync_fn=t_fsync;o.close_fn=t_close;o.rename_fn=t_rename;o.unlink_fn=t_unlink;o.sha256_path_fn=t_sha;sedit_document_test_io(&o);}
static int exact_file(const char*p,const char*s,size_t n){char b[64];FILE*f=fopen(p,"rb");if(!f)return 0;size_t z=fread(b,1,sizeof b,f);fclose(f);return z==n&&!memcmp(b,s,n);}
static int temp_count(const char*dir){DIR*d=opendir(dir);if(!d)return-1;int n=0;struct dirent*e;while((e=readdir(d)))if(strstr(e->d_name,".sedit.")&&strstr(e->d_name,".tmp"))n++;closedir(d);return n;}
#endif
int main(int argc,char**argv){
 const char*src="#define OPEN { \\\n+  1\nint main(void) { /* } */ const char *s=\"{\"; return (2); }\n/* unterminated";
 SeditLexer l;sedit_lex_init(&l);OK("chunk1",sedit_lex_feed(&l,src,25));OK("chunk2",sedit_lex_feed(&l,src+25,strlen(src)-25));OK("finish",sedit_lex_finish(&l));OK("keyword",has(&l,SEDIT_T_KEYWORD,"return",src));OK("type",has(&l,SEDIT_T_TYPE,"int",src));OK("comment",has(&l,SEDIT_T_COMMENT,"/* } */",src));uint32_t m;int u;const char*brace=strstr(src,"main(void) {")+11;OK("normal brace paired",sedit_pair_mate(&l,(uint32_t)(brace-src),&m,&u)&&!u);OK("comment brace excluded",!sedit_pair_mate(&l,(uint32_t)(strstr(src,"/* } */")-src+3),&m,&u));sedit_lex_free(&l);
 const char*boundary="int café=.12; /* split */ return (café); // tail\n";Ref bref;ref_scan(boundary,strlen(boundary),&bref);SeditLexer whole;sedit_lex_init(&whole);sedit_lex_feed(&whole,boundary,strlen(boundary));sedit_lex_finish(&whole);OK("independent reference agrees on readable witness",lex_ref_equal(&whole,&bref));OK("every split boundary is invisible",check_all_splits(boundary,strlen(boundary),&bref));OK("split witness keyword",has(&whole,SEDIT_T_KEYWORD,"return",boundary));OK("split witness block comment",has(&whole,SEDIT_T_COMMENT,"/* split */",boundary));sedit_lex_free(&whole);
 char random_src[8192];size_t rw=0;const char*atoms[]={"int ","x=.5;","/* [ ] */","return ","(x);","// }\n","\"{utf8-é}\";","#define Q(x) \\\n (x)\n"};unsigned seed=718;for(int ri=0;ri<200;ri++){seed=seed*1664525u+1013904223u;const char*a0=atoms[seed%8];size_t an=strlen(a0);if(rw+an<sizeof random_src){memcpy(random_src+rw,a0,an);rw+=an;}}SeditLexer oracle;sedit_lex_init(&oracle);sedit_lex_feed(&oracle,random_src,rw);sedit_lex_finish(&oracle);int random_ok=1;for(int trial=0;trial<64;trial++){SeditLexer q;sedit_lex_init(&q);size_t at=0;while(at<rw){seed=seed*1664525u+1013904223u;size_t z=1+seed%47;if(z>rw-at)z=rw-at;if(!sedit_lex_feed(&q,random_src+at,z))random_ok=0;at+=z;}if(!sedit_lex_finish(&q)||!lex_equal(&oracle,&q))random_ok=0;sedit_lex_free(&q);}OK("randomized split schedules equal independent one-feed oracle",random_ok);sedit_lex_free(&oracle);
 rw=0;memcpy(random_src,"int x=1+2;\n",11);rw=11;int edit_ok=1;for(int step=0;step<80;step++){seed=seed*1664525u+1013904223u;size_t at=rw?seed%(rw+1):0;seed=seed*1664525u+1013904223u;int op=seed%5;if((op==1||op==2)&&rw){size_t del=1+seed%5;if(at==rw)at--;if(del>rw-at)del=rw-at;memmove(random_src+at,random_src+at+del,rw-at-del);rw-=del;}if(op!=1){const char*a0=atoms[(seed>>8)%8];size_t an=strlen(a0);if(op==3&&an>1)an/=2;if(rw+an<sizeof random_src){memmove(random_src+at+an,random_src+at,rw-at);memcpy(random_src+at,a0,an);rw+=an;}}Ref rr;ref_scan(random_src,rw,&rr);SeditLexer q;sedit_lex_init(&q);sedit_lex_feed(&q,random_src,rw);sedit_lex_finish(&q);if(!lex_ref_equal(&q,&rr)||!check_all_splits(random_src,rw,&rr))edit_ok=0;sedit_lex_free(&q);}OK("seeded insert delete replace split join edits match independent scanner after every edit and feed split",edit_ok);
 const char*num="1+2 1e+2 0x1p-3";Ref nr;ref_scan(num,strlen(num),&nr);SeditLexer nl;sedit_lex_init(&nl);sedit_lex_feed(&nl,num,strlen(num));sedit_lex_finish(&nl);OK("pp-number signs only follow exponent markers",lex_ref_equal(&nl,&nr)&&nl.token_count==4);sedit_lex_free(&nl);
 char p[1024];uint32_t line;OK("arg location",!sedit_document_location("colon:name.c:42",p,sizeof p,&line)&&!strcmp(p,"colon:name.c")&&line==42);OK("primary diagnostic",!sedit_document_diagnostic("colon:name.c:9: error: bad",p,sizeof p,&line)&&line==9);OK("link diagnostic",!sedit_document_diagnostic("  at colon:name.c:7",p,sizeof p,&line)&&line==7);OK("reject column",sedit_document_diagnostic("a.c:2:3: error: bad",p,sizeof p,&line)!=0);
 OK("reject zero line",sedit_document_location("a.c:0",p,sizeof p,&line)!=0);OK("reject overflow line",sedit_document_location("a.c:4294967296",p,sizeof p,&line)!=0);OK("reject multiline diagnostic",sedit_document_diagnostic("a.c:2: error: x\nmore",p,sizeof p,&line)!=0);OK("reject unrelated text",sedit_document_diagnostic("a.c:2: note: x",p,sizeof p,&line)!=0);
 if(argc<2)return 2;char f[1024],f2[1024],linkp[1024],hard[1024];snprintf(f,sizeof f,"%s/a.c",argv[1]);snprintf(f2,sizeof f2,"%s/b.c",argv[1]);snprintf(linkp,sizeof linkp,"%s/l.c",argv[1]);snprintf(hard,sizeof hard,"%s/h.c",argv[1]);FILE*fp=fopen(f,"wb");fwrite("a\r\nb\r\n",1,6,fp);fclose(fp);symlink("a.c",linkp);SeditDocument d;sedit_document_init(&d);OK("load symlink",!sedit_document_load(&d,linkp));OK("CRLF detected",d.eol==SEDIT_EOL_CRLF);OK("physical target",strstr(d.target_path,"/a.c")!=NULL);OK("atomic save",sedit_document_save(&d,NULL,"a\nbb\n",5,0,0)==SEDIT_SAVE_OK);char b[32]={0};fp=fopen(f,"rb");size_t n=fread(b,1,sizeof b,fp);fclose(fp);OK("CRLF preserved",n==7&&!memcmp(b,"a\r\nbb\r\n",7));OK("symlink preserved",lstat(linkp,&d.opened_stat)==0&&S_ISLNK(d.opened_stat.st_mode));
 stat(f,&d.opened_stat);fp=fopen(f2,"wb");fwrite("other",1,5,fp);fclose(fp);unlink(linkp);symlink("b.c",linkp);OK("symlink retarget is conflict",sedit_document_save(&d,NULL,"mine",4,0,0)==SEDIT_SAVE_CONFLICT);memset(b,0,sizeof b);fp=fopen(f,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Cancel preserves old physical target",n==7&&!memcmp(b,"a\r\nbb\r\n",7));fp=fopen(f2,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Cancel preserves current physical target",n==5&&!memcmp(b,"other",5));struct stat link_before,b_before;stat(f2,&b_before);lstat(linkp,&link_before);OK("Overwrite publishes to currently resolved target",sedit_document_save(&d,NULL,"mine",4,1,0)==SEDIT_SAVE_OK&&strstr(d.target_path,"/b.c")!=NULL);struct stat link_after,b_after;lstat(linkp,&link_after);stat(f2,&b_after);OK("Overwrite preserves symlink and replaces current target inode",S_ISLNK(link_after.st_mode)&&b_before.st_ino!=b_after.st_ino);fp=fopen(f,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Overwrite leaves former target exact",n==7&&!memcmp(b,"a\r\nbb\r\n",7));char saveas[1024];snprintf(saveas,sizeof saveas,"%s/save-as.c",argv[1]);OK("Save As publishes only chosen path",sedit_document_save(&d,saveas,"copy",4,0,0)==SEDIT_SAVE_OK);fp=fopen(f2,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("Save As leaves symlink target exact",n==4&&!memcmp(b,"mine",4));lstat(linkp,&link_after);OK("Save As leaves symlink intact",S_ISLNK(link_after.st_mode));unlink(linkp);symlink("a.c",linkp);sedit_document_free(&d);sedit_document_init(&d);OK("reload original lane for fault tests",!sedit_document_load(&d,linkp));
#ifdef SEDIT_TEST
 set_fault(3);OK("write EINTR is retried",sedit_document_save(&d,NULL,"a\nbb\n",5,0,0)==SEDIT_SAVE_OK);set_fault(4);OK("short writes complete",sedit_document_save(&d,NULL,"a\nbb\n",5,0,0)==SEDIT_SAVE_OK);int stages[]={1,2,5,6,7,8,9,10};const char*names[]={"create ENOSPC","write ENOSPC","chmod failure","fsync failure","close failure","rename failure","hash failure","unlink cleanup failure"};const char*ops[]={"create temp","write temp","chmod temp","fsync temp","close temp","rename temp","hash current file","write temp"};for(size_t si=0;si<sizeof stages/sizeof stages[0];si++){set_fault(stages[si]);d.dirty=1;OK(names[si],sedit_document_save(&d,NULL,"changed",7,0,0)==SEDIT_SAVE_ERROR);OK("failed save retains dirty state",d.dirty==1);OK("failed save retains exact operation",strstr(d.error,ops[si])!=NULL);OK("failed save leaves original bytes exact",exact_file(f,"a\r\nbb\r\n",7));if(stages[si]==10)OK("unlink failure reports explicitly correct retained temp",unlinks==1&&temp_count(argv[1])==1);else OK("failed save leaves no temp",temp_count(argv[1])==0);}sedit_document_test_io(NULL);
#endif
 fp=fopen(f,"wb");fwrite("external",1,8,fp);fclose(fp);OK("hash conflict",sedit_document_save(&d,NULL,"mine",4,0,0)==SEDIT_SAVE_CONFLICT);sedit_document_free(&d);sedit_document_init(&d);OK("reload",!sedit_document_load(&d,f));link(f,hard);OK("hardlink refusal",sedit_document_save(&d,NULL,"new",3,0,0)==SEDIT_SAVE_HARDLINK);OK("explicit break",sedit_document_save(&d,NULL,"new",3,0,1)==SEDIT_SAVE_OK);struct stat a,h;stat(f,&a);stat(hard,&h);OK("break retained peer",a.st_ino!=h.st_ino);sedit_document_free(&d);
 fp=fopen(f2,"wb");fwrite("\xef\xbb\xbf" "a\r\nb\rc\nz",1,11,fp);fclose(fp);sedit_document_init(&d);OK("mixed EOL plus BOM loads",!sedit_document_load(&d,f2)&&d.eol==SEDIT_EOL_MIXED&&d.bom);OK("explicit EOL choice",!sedit_document_set_eol(&d,SEDIT_EOL_CR));OK("BOM and no-final-newline save",sedit_document_save(&d,NULL,d.text,d.len,0,0)==SEDIT_SAVE_OK);memset(b,0,sizeof b);fp=fopen(f2,"rb");n=fread(b,1,sizeof b,fp);fclose(fp);OK("chosen CR encoding exact",n==10&&!memcmp(b,"\xef\xbb\xbf" "a\rb\rc\rz",10));sedit_document_free(&d);
 return fail?1:0;
}
