#!/usr/bin/env node
// NetSurf Lane 4 content coverage: the in-tree image decoders exercised
// IN-APP (probe risk-3: "compiled but not exercised"), the data: fetcher,
// the error-page system, and the Lane 4 welcome/desktop-icon seeds.
//
//   - images.html (generated by tools/mkwebfixtures.js with its binary
//     fixtures): one 32x32 solid-colour image per decoder — GIF red
//     (libnsgif), BMP green + ICO blue (libnsbmp), PNG orange (libpng
//     in core), JPEG teal (libjpeg in core since 0448/#93 flipped
//     WITH_JPEG on) — plus a base64 data: URI GIF (magenta, the data
//     fetcher feeding a decoder) and a width/height-scaled re-use of
//     the GIF (the scaled-bitmap plot path). The decoded colours must
//     land on the framebuffer at the stacked block offsets.
//   - a data:text/html,... URL straight from the command line renders
//     (main.c's scheme detection — a bare "://" test used to send
//     scheme-only urls down the file path).
//   - a MISSING file:// path produces NetSurf's real fetch-error page
//     (title from Messages "FetchErrorTitle"), not a crash or a blank
//     window — and the browser still navigates/exits cleanly after.
//   - a bare `netsurf` opens the baked welcome page (about:welcome ->
//     resource:welcome.html -> /usr/share/netsurf/welcome.html): navy
//     brand band, body text, and the about:logo netsurf.png decoded
//     top-right (PNG decode through the resource fetcher).
//   - the Desktop seed: /root/Desktop/netsurf is a symlink to
//     /usr/bin/netsurf (the standard app-icon convention).
//
// Run: node tests/kernel/test_netsurf_content_e2e.js
'use strict';
const fs = require('fs');
const path = require('path');
const { driveBoot, freshImage } = require('./lib/drive.js');

const ROOT = path.resolve(__dirname, '../..');

let failures = 0;
function check(name, cond, extra) {
  if (cond) { console.log('  ok   ' + name); }
  else { console.log('  FAIL ' + name + (extra !== undefined ? '  ' + extra : '')); failures++; }
}

/* ---- seed boot, then plant images.html + the binary fixtures ---- */
const { dir: tmp, image } = freshImage('os-nscontent-');
driveBoot('true', { image });

{
  const COMMON = require(path.join(ROOT, 'os', 'os-common.js'));
  const { BLOCK_FS } = require(path.join(ROOT, 'host.js'));
  const rootStore = new COMMON.NodeFileStore(fs, image.slice(0, -4) + '-root.img', false);
  const rfs = BLOCK_FS.createV4(rootStore);
  const W = 0x40 | 0x200 | 1; /* O_CREAT|O_TRUNC|O_WRONLY */
  const TDIR = path.join(ROOT, 'vendor', 'netsurf', 'test');
  rfs.mkdir('/root/img', 0o755);
  const plant = (rel, dst) => {
    const bytes = fs.readFileSync(path.join(TDIR, rel));
    const fd = rfs.open(dst, W, 0o644);
    rfs.write(fd, bytes, bytes.length);
    rfs.close(fd);
  };
  plant('images.html', '/root/images.html');
  for (const f of ['red.gif', 'green.bmp', 'blue.ico', 'orange.png', 'teal.jpg']) {
    plant(path.join('img', f), '/root/img/' + f);
  }
  rootStore.flush();
  rootStore.close();
}

/* PPM helpers (the netsurf-e2e pattern) */
function parsePPMs(buf, names) {
  const shots = {};
  let off = 0;
  for (const name of names) {
    const head = buf.toString('latin1', off, off + 32);
    const m = head.match(/^P6\n(\d+) (\d+)\n255\n/);
    if (!m) throw new Error('bad ppm stream at ' + name + ': ' + JSON.stringify(head));
    const w = +m[1], h = +m[2];
    const data = off + m[0].length;
    shots[name] = { w, h, data: buf.slice(data, data + w * h * 3) };
    off = data + w * h * 3;
  }
  return shots;
}
const px = (s, x, y) => [s.data[(y * s.w + x) * 3],
                         s.data[(y * s.w + x) * 3 + 1],
                         s.data[(y * s.w + x) * 3 + 2]];
const near = (p, rgb, tol = 4) => Math.abs(p[0] - rgb[0]) <= tol &&
                                  Math.abs(p[1] - rgb[1]) <= tol &&
                                  Math.abs(p[2] - rgb[2]) <= tol;
const WHITE = [255, 255, 255];
function regionCount(s, pred, x0, y0, x1, y1) {
  let n = 0;
  for (let y = y0; y < Math.min(y1, s.h); y++) {
    for (let x = x0; x < Math.min(x1, s.w); x++) {
      if (pred(px(s, x, y))) n++;
    }
  }
  return n;
}

/* Post-title-barrier settle (see test_netsurf_e2e.js) */
const pollStable = (sid, out) => [
  `wmctl shot ${sid} ${out}`,
  `for i in $(seq 1 100); do sleep 0.1; wmctl shot ${sid} /root/poll.ppm; ` +
  `cmp -s /root/poll.ppm ${out} && break; cp /root/poll.ppm ${out}; done`,
];

/* the shot echo is GATED on the settled ppm existing, and the closed
 * echo on the close being accepted, so a leg that never found its
 * window cannot print success markers (its `wait win` timeout also
 * hard-fails the test via driveBoot's 0171 rule) */
const leg = (cmd, title, out, tag) => [
  `${cmd} &`,
  `wmctl wait win "${title}" 30000`,
  `SID=$(wmctl list | grep "\t${title}$" | sed "s/[^0-9].*//")`,
  ...pollStable('$SID', out),
  `[ -s ${out} ] && echo shot-${tag}-ok`,
  `wmctl close $SID && echo close-sent-${tag}`,
  `wmctl wait nowin "${title}" 8000`,
  `echo closed-${tag}-ok`,
];

/* data:text/html URL — %20 for spaces, %23 for #; attribute quotes are
 * fine inside the shell single-quoted argument */
const DATA_URL = 'data:text/html,<html><head><title>DataDoc</title></head>' +
  '<body%20style="margin:0"><div%20style="width:200px;height:100px;' +
  'background:%230000ff"></div></body></html>';

/* the missing-file error page title (the file fetcher 404s a missing
 * path and the query page titles itself from Messages "Not found") */
const ERR_TITLE = 'Not found';

/* ---- session A ---- */
const out = driveBoot([
  'readlink /root/Desktop/netsurf && echo LINK-OK',
  ...leg('netsurf /root/images.html', 'Images', '/root/i.ppm', 'images'),
  ...leg(`netsurf '${DATA_URL}'`, 'DataDoc', '/root/d.ppm', 'data'),
  ...leg('netsurf /root/no-such-page.html', ERR_TITLE, '/root/e.ppm', 'err'),
  ...leg('netsurf', 'Welcome to gucOS', '/root/w.ppm', 'welcome'),
], { image, timeout: 420000, maxBuffer: 64 * 1024 * 1024 }).stdout;

check('desktop icon: /root/Desktop/netsurf -> /usr/bin/netsurf',
      out.includes('/usr/bin/netsurf') && out.includes('LINK-OK'));
for (const tag of ['images', 'data', 'err', 'welcome']) {
  check(`${tag} rendered + shot`, out.includes(`shot-${tag}-ok`));
  check(`${tag} window closed`, out.includes(`closed-${tag}-ok`));
}

/* ---- session B: read the shots back ---- */
const NAMES = ['i', 'd', 'e', 'w'];
const back = driveBoot('cat ' + NAMES.map(n => '/root/' + n + '.ppm').join(' ') + '\n',
  { image, encoding: null, maxBuffer: 64 * 1024 * 1024 });
const shots = parsePPMs(back.stdout, NAMES);

/* i: every decoder's colour lands at its stacked block offset —
 * blocks are 32px tall from the origin, the scaled GIF 64px, the JPEG
 * appended after it at y 224 (0448/#93: WITH_JPEG + vendored libjpeg) */
{
  const s = shots.i;
  const IMGS = [
    [16, 16, [255, 0, 0], 'GIF (libnsgif) red'],
    [16, 48, [0, 200, 0], 'BMP (libnsbmp) green'],
    [16, 80, [0, 0, 255], 'ICO (libnsbmp) blue'],
    [16, 112, [255, 128, 0], 'PNG (libpng) orange'],
    [16, 144, [255, 0, 255], 'data: URI GIF magenta'],
    [32, 192, [255, 0, 0], 'scaled GIF (64x64) red'],
    [16, 240, [0, 128, 128], 'JPEG (libjpeg) teal'],
  ];
  for (const [x, y, rgb, label] of IMGS) {
    check(`i: ${label} at (${x},${y})`, near(px(s, x, y), rgb),
          String(px(s, x, y)));
  }
  check('i: white right of the 32px images', near(px(s, 80, 16), WHITE),
        String(px(s, 80, 16)));
  check('i: scaled image really 64px wide',
        near(px(s, 56, 192), [255, 0, 0]) && near(px(s, 80, 192), WHITE),
        `${px(s, 56, 192)} | ${px(s, 80, 192)}`);
}

/* d: the data:text/html document rendered — blue 200x100 at origin */
{
  const s = shots.d;
  check('d: data: URL blue block at (100,50)', near(px(s, 100, 50), [0, 0, 255]),
        String(px(s, 100, 50)));
  check('d: white outside the block at (300,50)', near(px(s, 300, 50), WHITE),
        String(px(s, 300, 50)));
}

/* e: the fetch-error page is a real rendered document — heading +
 * body text (dark glyph pixels), not blank, not a crash */
{
  const s = shots.e;
  const dark = regionCount(s, (p) => p[0] < 100 && p[1] < 100 && p[2] < 100,
                           0, 0, s.w, s.h - 18);
  check('e: error page has heading/body glyphs', dark > 200, `dark=${dark}`);
}

/* w: the welcome page — navy brand band up top, white body, text,
 * and the about:logo image (non-navy ink inside the band's top-right
 * float box) proving PNG decode through the resource fetcher */
{
  const s = shots.w;
  const NAVY = [0, 0, 128];
  check('w: brand band navy at (400,20)', near(px(s, 400, 20), NAVY),
        String(px(s, 400, 20)));
  check('w: white body below the band', near(px(s, 400, 300), WHITE),
        String(px(s, 400, 300)));
  const dark = regionCount(s, (p) => p[0] < 100 && p[1] < 100 && p[2] < 100,
                           0, 80, s.w, s.h - 18);
  check('w: body text glyphs present', dark > 300, `dark=${dark}`);
  /* the 32x32 logo floats right inside the band: x 748..780, y 12..44 */
  const logo = regionCount(s, (p) => !near(p, NAVY, 24) && !near(p, WHITE, 24),
                           744, 10, 784, 46);
  check('w: about:logo decoded (non-navy ink top-right)', logo > 40,
        `logo=${logo}`);
}

fs.rmSync(tmp, { recursive: true, force: true });

console.log(failures === 0 ? 'PASS test_netsurf_content_e2e'
                           : `FAIL test_netsurf_content_e2e (${failures})`);
process.exit(failures === 0 ? 0 : 1);
